### ISSUE TITLE
Add `to_hex(&self) -> String` to `FieldElement` of a `IsPrimeField`

### ISSUE THREAD

**Issue by MauroToscano** [lambdaclass/lambdaworks#104]
Add `to_hex(&self) -> String` function to `FieldElement` and implement it where needed

This function should create an hexstring representing the number in `FieldElement`. It should abstract the user from the internal representation, so if the number is in Montgomery form, it should convert it back to the original form before returning the element.

**Comment by ilitteri** [comment]
We could use the [hex](https://docs.rs/hex/latest/hex/index.html) crate and implement [its traits](https://docs.rs/hex/latest/hex/index.html#traits) and merge this issue with #103

**Comment by lognorman20** [comment]
Why should this method be implemented in `IsField` instead of `FieldElement`? I understand `IsField` to be a trait that adds field behavior to a struct, so returning a hex string of the number in `IsField` doesn't seem as useful as returning the hex string of a `FieldElement`.

**Comment by MauroToscano** [comment]
You're right @iognorman20. I have changed it to be on `FieldElement`. As a sidenote, it would also be useful if it can be a const fn. If any other issue arises feel free to ask

**Comment by emirsoyturk** [comment]
I am looking this issue currently.
