### ISSUE TITLE
Generalize `IsMontgomeryConfiguration`  and `MontgomeryBackendPrimeField`

### ISSUE THREAD

**Issue by GianfrancoBazzani** [lambdaclass/lambdaworks#126]
In order to solve https://github.com/lambdaclass/lambdaworks/issues/95 without repeat code i tried to generalize `IsMontgomeryConfiguration`  trait and  `MontgomeryBackendPrimeField` struct to allow usage with any `UnsignedInteger`.

Tried something like this:
![image](https://user-images.githubusercontent.com/55500596/221582398-a973d1ec-b6a7-4197-8e90-26bcc7b45f30.png)

If  i use  a generic U: `IsUnsignedInteger` :

![image](https://user-images.githubusercontent.com/55500596/221582869-381b0f54-729b-416d-bf1e-1bbb8f33d13f.png)

Any idea to define a generic <U> to generalize any type `UnsignedInteger<_>` struct like?

**Comment by MauroToscano** [comment]
Don't generalize it over the trait, we just need it to work with UnsignedInteger<u: usize> for now. This will enable the auto paramater generator we added to work smoothly, since rust don't like const functions in traits.

**Comment by MauroToscano** [comment]
This backend is to make generally optimized code and enable a fast implementation of any field. The IsUnsignedInteger is for everything to keep working if you want to make a really specific optimization, or swap the native type for another one.

**Comment by MauroToscano** [comment]
Leaving that aside, the problem there is that you are using a trait, so you can't use `UnsignedInteger` functions directly if you define the variable as `U`. You are limited to the trait functions, because the U could be something different.

**Comment by GianfrancoBazzani** [comment]
Tanks a lot Mauro, you are truly a Rust warlock. So instead of generalize for any object with `IsUnsignedInteger` trait implementation, I generalized for any `NUM_LIMBS` constant value and used `UnsignedInteger<NUM_LIMBS>` to generalize for any object following custom multiprecision unsigned integer struct like (Types: U256, U384,....). Seems Works and passes the tests:

![Screenshot from 2023-02-27 15-55-39](https://user-images.githubusercontent.com/55500596/221598653-845496a1-4cb2-4459-9c77-9f2049828f33.png)

**Comment by GianfrancoBazzani** [comment]
> Leaving that aside, the problem there is that you are using a trait, so you can't use `UnsignedInteger` functions directly if you define the variable as `U`. You are limited to the trait functions, because the U could be something different.

I see the difference, thanks a lot. Generalizing through NUM_LIMS I can access all methods of `Unsigned Integer` that is what I wanted.
