### ISSUE TITLE
API for transcript_to_field and transcript_to_usize

### ISSUE THREAD

**Issue by pablodeymo** [lambdaclass/lambdaworks#174]
We need an API to generate Field elements from the Transcript.

We have this methods:

* `pub fn transcript_to_field(transcript: &mut Transcript) -> FE`

* `fn transcript_to_usize(transcript: &mut Transcript) -> usize`

**Comment by MauroToscano** [comment]
It needs to implement the following secure algorithm: 

https://datatracker.ietf.org/doc/id/draft-irtf-cfrg-hash-to-curve-06.html#name-hashing-to-a-finite-field

We may also need to check how to make sure the function is constant time in Rust

**Comment by MauroToscano** [comment]
Currently this is implemented under `IsStarkTranscript, but I think it could be just done for all transcripts

**Comment by MauroToscano** [comment]
Superseeded by #789
