### ISSUE TITLE
Change `assert!`s for `debug_assert!`s

### ISSUE THREAD

**Issue by MauroToscano** [lambdaclass/lambdaworks#21]
Some functions should return a `Result`instead of using an `assert` because doing the latter would panic in runtime. 

In general, if you don't have any choice but to panic it is better to describe the cases in which that function would panic and why in the documentation.

For this issue, we just want to replace these assertions with debug assertions. We'll address the `Result` in another issue.

An example would be [this](https://github.com/lambdaclass/lambdaworks/blob/main/math/src/elliptic_curve/traits.rs#L71-L74).

**Comment by josepchetrit12** [comment]
Can you write a short description? Thank you

**Comment by ilitteri** [comment]
> Can you write a short description? Thank you

Description added!

**Comment by josepchetrit12** [comment]
Can I take it?

**Comment by ilitteri** [comment]
> Can I take it?

Sorry for the delay, sure you can take it!
