### ISSUE TITLE
Random Field Element

### ISSUE THREAD

**Issue by MauroToscano** [lambdaclass/lambdaworks#25]
Implement the `rand` traits for `FieldElement<F>` where `F: IsFIeld`.

**Comment by gluax** [comment]
UX should be considered here more. Rather than just defining a `random` method that uses a generic as an argument, we should implement the `rand` traits for the types.

It is more convenient and better for user experience when using the library.

**Comment by ilitteri** [comment]
> UX should be considered here more. Rather than just defining a `random` method that uses a generic as an argument, we should implement the `rand` traits for the types.
> 
> It is more convenient and better for user experience when using the library.

Thanks for the suggestion, you're right, we'll update the description!

**Comment by ilitteri** [comment]
> Can I take it?

Sure!

**Comment by GianfrancoBazzani** [comment]
Hi,  i cannot find `IsFielElement` trait should it be included in `IsField`?

**Comment by ilitteri** [comment]
> Hi, I cannot find `IsFielElement` trait, should it be included in `IsField`? or maybe `IsField` should be renamed to `IsFielElement`? Sorry for my ignorance, I'm not familiar with rust naming conventions yet.

You're right! `IsFieldElement` was the former name of `IsField`. You should implement it for `IsField`.

**Comment by ilitteri** [comment]
> Hi, I cannot find `IsFielElement` trait, should it be included in `IsField`? or maybe `IsField` should be renamed to `IsFielElement`? Sorry for my ignorance, I'm not familiar with rust naming conventions yet.

The description is updated.

**Comment by MauroToscano** [comment]
This is done, though the code is not clear on that, we can create another issue to move it around
