### ISSUE TITLE
Add `proptest::Arbitrary` support

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambdaworks#414]
In [_cairo-vm_](https://github.com/lambdaclass/cairo-vm/blob/c2b7f1818db110869012f75ad72b9f97f40e9c5d/felt/src/arbitrary.rs#L8) we implement [`proptest::Arbitrary`](https://docs.rs/proptest/latest/proptest/) on our `Felt252` type to use it on proptests. We could move that code to `UnsignedInteger`, to allow lib users to more easily proptest their projects. This also should help reduce the amount of code repetition in _lambdaworks_' tests.

**Comment by PatStiles** [comment]
Hi interested in taking this on but want to make sure it isn't stale?

**Comment by MauroToscano** [comment]
We are not using proptest a lot lately, and we are trying to reduce it's usage and use more fuzzers and normal tests. But no one is doing it, you can add it. Please check everything compiles with Wasm target if you do so, because it tends to give issues with that.
