### ISSUE TITLE
Add subgroup check to pairings

### ISSUE THREAD

**Issue by MauroToscano** [lambdaclass/lambdaworks#543]
The inputs of the [pairing function](https://github.com/lambdaclass/lambdaworks/blob/6ad2e4620128962657d58a667e1b26d6e948d461/math/src/elliptic_curve/short_weierstrass/curves/bls12_381/pairing.rs#L20-L41) need to be checked to belong to the $r$-torsion of the curve. The naive implementation would be to check that $rG$ is the point at infinity. There are better approaches. See [here](https://hackmd.io/@yelhousni/bls12_subgroup_check).

It should be added to the pairing module of the curve

**Comment by PatStiles** [comment]
I'll take a shot at this

**Comment by RajeshRk18** [comment]
I have just done with adding efficient subgroup checks (using endomorphism) for G1 and G2 here: https://github.com/RajeshRk18/lambdaworks/tree/add/subgroup-checks

**Comment by MauroToscano** [comment]
This was solved with #649
