### ISSUE TITLE
Error instead of panicking on `inv` function for `FieldElement`

### ISSUE THREAD

**Issue by MauroToscano** [lambdaclass/lambdaworks#545]
Inv should not panic. It should be changed to an error

- [ ] Add `InvZeroError`, unwrap where before it would panic
- [ ] Remove unwraps

First task should be done and merged before the second one.

**Comment by dbejarano820** [comment]
I can take this one!

**Comment by diegokingston** [comment]
Solved with https://github.com/lambdaclass/lambdaworks/pull/546
