### ISSUE TITLE
Bug: UnsignedInteger reveals the secret value

### ISSUE THREAD

**Issue by RajeshRk18** [lambdaclass/lambdaworks#587]
Curent implementation of `UnsignedInteger` reveals the secret value. 

I have reproduced the issue here: https://gist.github.com/RajeshRk18/70ebddf1060ea480cbd87db71bd89152.

**Recommendation:**

Wrap the limb array with `Box` and use `clone` wherever values have been moved as cloning the `Box` is cheap and the limbs won't be moved.

**Comment by MauroToscano** [comment]
This looks out of scope, and more an issue of traditional cryptography. It also forces everything to be in the heap. And it can be solved by a wrapper.

**Comment by RajeshRk18** [comment]
Yeah, more of an application side crypto issue. Crypto libraries like libsecp256k1 directly use Scalar for secret keys. 

But we have to be assured that this doesn't impact Lambdaworks.

**Comment by MauroToscano** [comment]
This can be re opened if it becomes an issue, I'm closing it since it seems out of scope. If it affects something in a proving system we can make a wrapper to fix this case
