### ISSUE TITLE
Cairo Prover: Prove Pure Cairo (non-starknet contract)

### ISSUE THREAD

**Issue by raphaelDkhn** [lambdaclass/lambdaworks#604]
Currently, the Cairo Prover proves only `casm.json` files from starknet contract. 

It would be nice to prove Non-Starknet contracts (pure Cairo programs) for Verifiable Computing.

**Comment by MauroToscano** [comment]
You can prove cairo0 programs! Instructions are in the [Cairo CLI](https://github.com/lambdaclass/lambdaworks/tree/main/provers/cairo-prover-cli)

**Comment by raphaelDkhn** [comment]
Yes thanks, but I need to prove Cairo1 programs

**Comment by MauroToscano** [comment]
Yes, the compiler of Cairo1 is missing proof mode. We added it ourselves but we got an issue with some programs using recursion, so we didn't release it. We will go back to add this in the future

**Comment by MauroToscano** [comment]
This is solved. Can be continued with #728
