### ISSUE TITLE
Improving Cairo programs with imputs

### ISSUE THREAD

**Issue by Cevedale** [lambdaclass/lambdaworks#617]
Here's a simple example of a main function in Cairo that takes input parameters:

type MyContract:
data: felt

func main(input_param1: felt, input_param2: felt) -> (result: felt):
// Perform some operations using the input parameters
// For example, let's add the two input parameters and store the result in the 'data' field.
data := input_param1 + input_param2

// Return the result
result := data
In this example:

MyContract is a simple contract with a single variable data of type felt (a 256-bit integer in Cairo).
The main function takes two input parameters, input_param1 and input_param2, both of type felt.
Inside the function, it performs a simple addition of the input parameters and stores the result in the data variable.
The result is then returned.
This is a very basic example, and in a real-world scenario, you would have more complex logic in your main function, interacting with the blockchain, other contracts, or external data.

Keep in mind that Cairo is often used for smart contracts, so the main function is typically called automatically when the contract is executed on the blockchain. If you have a specific use case or more details about what you're looking for, feel free to provide additional information!

**Comment by MauroToscano** [comment]
This should be done in the VM, since Cairo1 programs are runned there. After that, we can discuss adding some public inputs
