### ISSUE TITLE
Implement constraint importer from gnark for usage within Groth16 prover

### ISSUE THREAD

**Issue by gabrielfior** [lambdaclass/lambdaworks#679]
As raised in this [comment](https://github.com/lambdaclass/lambdaworks/pull/612#discussion_r1382018388), it would be great if we could validate the algorithms with intermediate results from other libraries, such as gnark.

The idea would be:
-> Implement a CSV importer of R1CS (for example, https://play.gnark.io/ outputs such a CSV representing the constraints, select `cubic equation` on the top right dropdown)
-> Convert said R1CS into a QAP representation, that we can then forward to the Groth16 prover
-> Write a test for said conversion, proving and verification

**Comment by diegokingston** [comment]
Solved
