### ISSUE TITLE
More efficient Montgomery CIOS

### ISSUE THREAD

**Issue by MauroToscano** [lambdaclass/lambdaworks#758]
Implement the more efficient CIOS algorithm from Gnark.

Bench with the finite field benches and confirm if there are improvements

https://hackmd.io/@gnark/modular_multiplication

**Comment by MauroToscano** [comment]
This has been done here, https://github.com/lambdaclass/lambdaworks/pull/766, but it didn't provide any measurable speedup. If we manage to make it go faster it can be used

**Comment by diegokingston** [comment]
Solved
