### ISSUE TITLE
Issue with Verifier Failing at Step 2 in Certain Cairo Programs

### ISSUE THREAD

**Issue by raphaelDkhn** [lambdaclass/lambdaworks#764]
I'm encountering an issue where the verifier fails at step 2, specifically at "Verify claimed polynomial," with certain Cairo programs.

Here's a detailed description of my process:

1. I used CairoVM to generate trace and memory files using the following command:
`cargo run ../cairo_programs/cairo-1-programs/with_input/array_input_sum.cairo --layout all_cairo --args '2 [1 2 3 4] 0 [9 8]' --trace_file ../cairo_programs/cairo-1-programs/with_input/array_input_sum.trace --memory_file ../cairo_programs/cairo-1-programs/with_input/array_input_sum.memory`

The Cairo program used was:

```
use array::ArrayTrait;

fn main(index_a: u32, array_a: Array<u32>, index_b: u32, array_b: Array<u32>) -> u32 {
    *array_a.at(index_a) + *array_b.at(index_b)
}
```

2. After generating the proof with Platinum prover successfully, I attempted to verify it. However, the verifier fails at step 2: "Verify claimed polynomial."

3. To test further, I tried with a different Cairo program:
```
use core::array::SpanTrait;

#[derive(Copy, Drop)]
struct Tensor {
    shape: Span<u32>,
    data: Span<u32>
}

fn main(tensor: Tensor) -> Tensor {
    tensor
}
```

Unfortunately, I encountered the same verifier issue.

4. Interestingly, the verifier works fine with the following Cairo program:
```
fn main(argc: u32) -> u8 {
    if argc == 0 {
        1_u8
    } else {
        0_u8
    }
}
```

This pattern leads me to believe that there might be a specific issue with the verifier in handling certain types of Cairo programs, particularly those involving arrays.

**Comment by Robertorosmaninho** [comment]
I think you missed `proof_mode` flag.

**Comment by raphaelDkhn** [comment]
> I think you missed `proof_mode` flag.

Oh you're right! Sorry for the bother!
