### ISSUE TITLE
Remove panics on the `inv` methods

### ISSUE THREAD

**Issue by jrchatruc** [lambdaclass/lambdaworks#77]
Currently the `inv` implementations for `U64PrimeField` and `U384PrimeField` both panic when dividing by zero. We should return an error instead. For this, we should use `thiserror`.

**Comment by josepchetrit12** [comment]
Can I take it?

**Comment by xqft** [comment]
@josepchetrit12 thanks! it's all yours

**Comment by josepchetrit12** [comment]
@xqft perfect! One question, have you implemented the first part in your PR, right? I'm talkin about `thiserror`.

**Comment by xqft** [comment]
Yes! I started implementing it to fix our test field but it would require work that's out of the scope of that PR. You can change the enum however you want though, I think I would add a `String` field to it for a more descriptive error message (like, "can't invert zero element"), but it's totally on you.

**Comment by MauroToscano** [comment]
I'm closing this issue. This is replaced by Issue #545, which is more specific and more reduced in scope, so it's easier to merge.
