### ISSUE TITLE
Feat(perf): Benchmark Plonky2 bit reversal vs current implementation

### ISSUE THREAD

**Issue by PatStiles** [lambdaclass/lambdaworks#786]
Plonky2 utilizes architecture aware implementations for inplace bit reversal. Benchmark to see what the performance improvement is and if it justifies the added complexity.

Ref: https://github.com/0xPolygonZero/plonky2/blob/a9060e61b8004525b6f84c69dd21ad1a5cd1c3b2/util/src/lib.rs#L110

**Comment by MauroToscano** [comment]
I'll move it to FFT/NTT issue #731 , as to avoid bloating the backlog
