### ISSUE TITLE
Does the stark prover support (perfect)zero knowledge?

### ISSUE THREAD

**Issue by XuyangSong** [lambdaclass/lambdaworks#850]
Can I use the stark-platinum-prover in situations that need to hide private data?

According to winterfell [Implement perfect zero-knowledge #9](https://github.com/facebook/winterfell/issues/9), it hasn't implemented the feature yet.

From an [article](https://reilabs.io/blog/introducing-hints-in-cairo-programming-language/), it mentioned:

> Currently, none of the generally available provers (such as StarkWare's SHARP and Stone, or Lambdaclass' lambdaworks) guarantee that data is not leaked in their proofs.

**Comment by MauroToscano** [comment]
It doesn't provide perfect privacy. You can use it but bearing that in mind.
