### ISSUE TITLE
`from_hex` panics if invalid but prefixed with 0x

### ISSUE THREAD

**Issue by FabijanC** [lambdaclass/lambdaworks#886]
E.g. all of the following panic:

```rust
U384::from_hex("0xOa")
U384::from_hex("0xm")
```

with the message:
```
Malformed hex expression.
```

But this expectedly returns an `Err(InvalidHexString)` instead of panicking:
```rust
U384::from_hex("0xaO")
```

**Comment by Oppen** [comment]
Thanks for the report @FabijanC! Turns out the subroutine checking the validity of the string was missing the first digit due to an off-by-one, and because of that it ended up dying in the `_unchecked` variant.
